### ISSUE TITLE
Typeahead list is showing horizontal scroll

### ISSUE THREAD

**Issue by contactrajiv08** [PredixDev/px-typeahead#10]
Hi,

Typeahead list is showing horizontal scroll bar. Is there any attribute available in px-typeahead to extend the width of list area to remove the horizontal scroll, like we have in px-dropdown (extend-dropdown="true" extend-dropdown-by="25") component.

![typeahead](https://cloud.githubusercontent.com/assets/7464756/23552269/fd94a0c6-0040-11e7-9a34-faa8da3f4399.png)

Thank You,
Rajiv

**Comment by runn-vermel** [comment]
There is currently nothing like it - you have 2 options:

1. write it yourself - you can probably use some of the same logic from px-dropdown
2. submit it as a feature request - this will take much longer, and might not happen.
