### ISSUE TITLE
px-typeahead component height is based on icon

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-typeahead#12]
When inspecting the px-typeahead component in Firefox the reported height is relative to the icon rather than the full component as was the case in 0.2.20. This causes some layout issues when used in a flex.

![pxtypeahead](https://cloud.githubusercontent.com/assets/1684641/23903478/93803e14-08bc-11e7-8027-02fe5f401385.png)

**Comment by randyaskin** [comment]
Not sure when this changed, but no longer seems to be the case. Closing.
