### ISSUE TITLE
Indication of no matches

### ISSUE THREAD

**Issue by leebickmtu** [PredixDev/px-typeahead#14]
It would be nice to give users some feedback that no items match the current type ahead search rather than just not showing anything at all.

Current behavior:
No dropdown shows, you're just left with what you typed and no indication of zero results.

Expected behavior:
Some indication that the search yielded no type ahead results. (Maybe show the dropdown with light text indicating no results).

**Comment by randyaskin** [comment]
I gave it the ol' college try, but it will take a bit of re-architecting. The team that built it did some funky stuff with async and debounce so the search term and results array are never in the state I need them in to display a message. Sorry, thought it might be a quick win. Feel free to submit a pull request!
