### ISSUE TITLE
px-typeahead-keydown not working

### ISSUE THREAD

**Issue by dilipchandima** [PredixDev/px-typeahead#19]
In PredixUI documentation says that px-typeahead-keydown event but it is not working
when see the code base in this event method "px-typeahead-keydown" is just the comment
The event method is "px-typeahead-search-input-change"

`/**
* fires an event when search input field changes
* @event px-typeahead-keydown
* @param {e} event
*/
 _onSearchInputChange: function(e){
   this.fire('px-typeahead-search-input-change', e);
 }`

**Comment by randyaskin** [comment]
Fixed in v2.0.6, should reflect on the API page as soon as it rebuilds.
