### ISSUE TITLE
Option to only notify the input value changed on mouse click or key press

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-typeahead#2]
At the moment input value change is triggered as the scroll through the list via arrow keys.

In my case this would trigger a potentially expensive operation so I would prefer to only notify the input value changed if the mouse is clicked (see #1) or the return key is pressed.

**Comment by runn-vermel** [comment]
Thanks for the comment!

V0.1.1 should fix this - input value is now only changed when the enter key is pressed after scroll.

**Comment by manderson23** [comment]
Thanks for the quick fixes.
