### ISSUE TITLE
Unable to bind selected value in px-typehead with angular 2 app

### ISSUE THREAD

**Issue by mailmrmanoj** [PredixDev/px-typeahead#20]
I'm trying to get the selected value in my `px-typehead` component that I have used in the angular app.

The docs of `px-typehead` says to use `value: string` to get the current value of the input [(docs)][1].But the searched element dosen't seem to bind with the `[(ngModel)]`.

Codepen link  [here][2]

I also tried by changing the `value` to `inputValue`/`input-value`/`[attr.input-value]` 

  [1]: https://www.predix-ui.com/#/elements/px-typeahead:property-value
  [2]: https://codepen.io/mailmrmanoj/pen/wrMRKJ

**Comment by randyaskin** [comment]
To be compatible with ngModel, custom elements need to provide ControlValueAccessor, which gives ngModel a way to set the value and listen to value changes. vaadin/angular2-polymer has `formElementDirective` that implements this for elements with iron-form-element behaviour (listening to valueChange/setting value). Others - including px-typeahead - need custom CVA implementation. See https://blog.thoughtram.io/angular/2016/07/27/custom-form-controls-in-angular-2.html for more.

**Comment by mailmrmanoj** [comment]
@randyaskin  Thanks.Is there any working fiddle with `px-typeahead` and `angular2`

**Comment by randyaskin** [comment]
Not that I have, no.
