### ISSUE TITLE
Selecting via the keyboard or mouse displayed value is broken

### ISSUE THREAD

**Issue by indresh-kumar** [PredixDev/px-typeahead#23]
Steps to reproduce:-
1) Go to demo page:- https://www.predix-ui.com/#/elements/px-typeahead:event-px-typeahead-item-selected
2) Search tes and then select 1st option i.e.  United States, it display "United Sta              tes" instead of "United States"
3) Should display whatever value selected from dropdown but selected display value add space:

![screen shot 2017-10-31 at 3 57 24 pm](https://user-images.githubusercontent.com/12592966/32248695-84232866-be54-11e7-945f-232635b72fca.png)
![screen shot 2017-10-31 at 3 57 37 pm](https://user-images.githubusercontent.com/12592966/32248705-891174f4-be54-11e7-8935-3ae00b5030e6.png)

**Comment by randyaskin** [comment]
Closed in v2.0.10.
