### ISSUE TITLE
Keyboard scroll won't work

### ISSUE THREAD

**Issue by jcheenatcode** [PredixDev/px-typeahead#24]
# Submit an Issue

## Expected behavior:
Using keyboard arrows should scroll.

##actual behavior
Using keyboard arrows should scroll.

## Steps to reproduce the problem:
Start searching in the search field.
Use keyboard arrows to scroll down
If the result list is has a scroll, using the keyboard arrows won't scroll

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Component Version: 2.0.10
Chrome: 62
Windows 10

## Screenshots (_optional, but very helpful_):
![px-typeahead-scroll-issue](https://user-images.githubusercontent.com/23624174/33078934-d0c1bd36-ce99-11e7-8039-d6edc8362f12.gif)

**Comment by randyaskin** [comment]
Fixed in v2.1.1. Ideally we should probably switch to iron-a11y instead of the custom handlers that were written. 🤷‍♂️

**Comment by jcheenatcode** [comment]
Thanks Randy! will take a look at iron-a11y.
