### ISSUE TITLE
Highlight Direction/Configuration

### ISSUE THREAD

**Issue by erikjswedberg** [PredixDev/px-typeahead#25]
Typeahead highlighting starts left-to-right and can highlight incorrectly in cases of repeated strings.  Consider the case in this [codepen](https://codepen.io/anon/pen/BYoYNE), where search strings occur twice in the same result:

Search Text: "las"
Expected behavior: "lastModifiedBy: **Las**sie"  <-bold within "Lassie"
Actual Behavior: "**las**tModifiedBy: Lassie"  <- bold within "lastModifiedBy"

Possible solutions:

- Add option to highlight text from the other direction, ex `highlight-direction: "reverse"`
- Allow `type="strings"` for default behavior and `type="objects"` with `local-candidates="[ { "key": "lastModifiedBy:", "text": "Lassie"}, { ... }, { ... } ]"` where highlighting is applied only to the "text" field
- Allow `type="html"` and `highlight="off"` where the user would include bolding manually, ex `local-candidates="[ "lastModifiedBy: <strong>Las</strong>sie", " ... ", " ... "]`"

**Comment by erikjswedberg** [comment]
Issue #8 is related to my second suggestion

**Comment by randyaskin** [comment]
My expectation would actually be that *both* instances of "las" would be highlighted. I'll consult with the design team.
