### ISSUE TITLE
Manually Handled Fuzzy Candidates Get Hidden

### ISSUE THREAD

**Issue by erikjswedberg** [PredixDev/px-typeahead#26]
Issue:  I would like a flag to allow/assert manual control of whether the suggestions get shown, even when the candidates don't contain the exact string as the input value, eg 
- `skip-internal-check=true`  (to skip the filter check in localCandidateSearch function)
- `remote-suggestions=['show all of these', 'on change', 'trust me they are good']`  (to use instead of localCandidates) (watch for changes, then put them into _suggestions)
- some other flag indicating I know what should be shown

Explanation:
The values I am putting into localCandidates are actually fuzzy search results, so they often do not exactly match the input. Because suggestions are only shown if they pass a literal text search internally, my fuzzy results are not shown.

Expected: searching "parn" shows option of "parent: hadoop-yarn"

Actual
![parn failure](https://user-images.githubusercontent.com/30904811/35708883-cc354336-0775-11e8-8d2a-0699f0bc19cf.png)

_localCandidateSearch("parn") returns empty, _suggestions becomes empty, so _isSuggestionsEmpty returns false, so the dom-if fails and nothing is shown

**Comment by randyaskin** [comment]
What are you using to perform the fuzzy search? Might just be easier to integrate something like http://fusejs.io/ and add a property for `allow-fuzzy`? We're always open to pull requests!

**Comment by erikjswedberg** [comment]
We're using Elastic Search.  Thanks!
