### ISSUE TITLE
Can't get the local-candidates to work with a component variable

### ISSUE THREAD

**Issue by Abhijith1** [PredixDev/px-typeahead#29]
I'm trying to get the `px-typeahead` to work for my app but I'm unable to figure out the right way to bind an array variable in my component to the `local-candidates` attribute.
Here's how my code looks like:

**app.component.html:**
`<px-typeahead placeholder="Enter text"  local-candidates="{{test}}">
</px-typeahead>`

I have a variable declared in my app.component.ts like this:
`test = ["Value1", "Value2"];`

But when I try searching for Value1/Value2, I don't see any suggestions by the typeahead. 
It works as expected when I hard code the above array inside the `local-candidates` in my html itself 
What Am I missing here?

**Comment by benoitjchevalier** [comment]
By the look of it you're using angular, but the polymer syntax for your bindings. Treat the typeahead as a native element and use angular bindings:
`<px-typeahead placeholder="Enter text" [local-candidates]="test"> </px-typeahead>`

**Comment by Abhijith1** [comment]
Couldn't get that to work either. :(
