### ISSUE TITLE
Add disabled property

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-typeahead#3]
To allow user input to be disabled. 

This would be consistent with other Predix UI components.

**Comment by runn-vermel** [comment]
@manderson23  - Why can't you just use the built in HTML5 disabled property?

**Comment by manderson23** [comment]
@runn-vermel elements like `px-dropdown` support an explicit disabled attribute at the web component level to set the attribute as appropriate on the tags within the component.

Wouldn't you need to support the same? The disabled attribute has to be added on the input within the component.

**Comment by runn-vermel** [comment]
@manderson23 You talked me into it ;)

V0.2.0 has a disabled feature :)

**Comment by manderson23** [comment]
Thanks again.
