### ISSUE TITLE
Px-typehead authentication header

### ISSUE THREAD

**Issue by eKutirRepo** [PredixDev/px-typeahead#33]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
Once you've created your code example, you can save it under a new url.
Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by eKutirRepo** [comment]
Hi Team,

   i am not able getting the Px-typehead auto complete box when i apply the authentication header in the px-typehead EX: **<px-typeahead max-suggestions="10" placeholder="Search.." style="background-color: #fff;" class="flex__item" id="reportString" header=[[header]]**  not give me any data

**Comment by evanjd** [comment]
@eKutirRepo `header` is not a property of `<px-typeahead>`.

**Comment by evanjd** [comment]
Closing as issue relates to a feature that does not exist. @eKutirRepo if you intended this as a feature request, please let me know and I'll raise something else that covers this.

Also in future, please fill out the issue form.

**Comment by eKutirRepo** [comment]
> @eKutirRepo `header` is not a property of `<px-typeahead>`.

Thank you evanjd,,but how to pass a Authenticate header in the <px-typeahead>.
so i have to pass each service call i have to pass Authorization Bearer (Token). so how to pass..pls help me
Ex:-my service url:--<px-typeahead max-suggestions="10" placeholder="Search.." style="background-color: #fff;" class="flex__item" id="reportString"  prefetch-url="http://localhost:8080/rest/api/v1/rc/getAllReportNames"></px-typeahead>

**Comment by evanjd** [comment]
> Thank you evanjd,,but how to pass a Authenticate header in the .

The component isn't currently capable of including headers you define to the prefetch or request services. I can raise a feature request if this is something you're wanting.

If the amount of suggestions isn't too high, as a workaround, you could retrieve the typeahead suggestions separate to the component then populate the `local-candidates` property yourself. eg.

```javascript
// Cache suggestions
let suggestions = fetch('https://my/suggestions/service', headers: { 'Authorization': 'Bearer abc123' });
// Massage data as needed so that suggestions is an array of strings

myPxTypeAheadEl.localCandidates = suggestions;
```
