### ISSUE TITLE
hitting enter from the input is not selecting the item

### ISSUE THREAD

**Issue by appagg** [PredixDev/px-typeahead#4]
1) from the demo
2) type in 'california'
3) only one item is in the suggestion
4) hit enter, the item is not selected and there's an error in the console
![screen shot 2016-12-02 at 11 35 52 am](https://cloud.githubusercontent.com/assets/1781887/20847617/ca646ca4-b883-11e6-8229-70dabfc82046.png)

**Comment by runn-vermel** [comment]
HI @appagg - Thanks for submitting an issue :)

This is fixed in version v0.2.11
