### ISSUE TITLE
Selecting via the keyboard when multiple options are displayed is broken

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-typeahead#6]
The item isn't selected after the following steps:

1. Type so that multiple selections are displayed
2. Use the cursor keys to select one of the items
3. Hit enter to select that item

To me this looks like a regression after the fix for #4 was added.

**Comment by runn-vermel** [comment]
Hi @manderson23 - Thanks for the issue!

I think i got it this time  (blush) - give it a whirl (v0.2.13) :)

**Comment by manderson23** [comment]
Thanks.
