### ISSUE TITLE
Throws JS error when dropdown list is empty

### ISSUE THREAD

**Issue by DaveFox** [PredixDev/px-typeahead#9]
When text is entered that doesn't match any result in a local-candidates array and a user presses the up or down arrow key on the keyboard, the component throws the following error: `Uncaught TypeError: Cannot read property 'classList' of undefined`

**Comment by runn-vermel** [comment]
I cannot reproduce this. @DaveFox - which browser/os did this happen on?

**Comment by runn-vermel** [comment]
Thanks for issue, @DaveFox, this should be fixed in v0.2.20
